### ISSUE TITLE
 insmod dw1000.ko fail

### ISSUE THREAD

**Issue by xingqing6210** [xueliu/dw1000-linux#2]
hi,
 compile the dw1000 driver , we also use the kernel 4.9.80, but insmod it report error, as following:

> pi@raspberrypi:~/rsp_linux/dw1000-linux $ ls
deca_version.h  dw1000.ko     dw1000.o       Makefile        README.md
dw1000.c        dw1000.mod.c  dw1000_regs.h  modules.order   rpi
dw1000.h        dw1000.mod.o  LICENSE        Module.symvers

> pi@raspberrypi:~/rsp_linux/dw1000-linux $ uname -a
Linux raspberrypi 4.9.80-v7+ #1098 SMP Fri Mar 9 19:11:42 GMT 2018 armv7l GNU/Li                     nux
pi@raspberrypi:~/rsp_linux/dw1000-linux $ modinfo dw1000.ko
filename:       /home/pi/rsp_linux/dw1000-linux/dw1000.ko
license:        GPL v2
author:         Xue Liu
description:    DW1000 IEEE 802.15.4 UWB Transceiver Driver
srcversion:     32CEED8C05896BF5DF99499
alias:          of:N*T*CdecaWave,dw1000C*
alias:          of:N*T*CdecaWave,dw1000
alias:          spi:dw1000
depends:
vermagic:       4.9.80-v7+ SMP mod_unload modversions ARMv7 p2v8

> pi@raspberrypi:~/rsp_linux/dw1000-linux $ insmod dw1000.ko
insmod: ERROR: could not insert module dw1000.ko: Operation not permitted
pi@raspberrypi:~/rsp_linux/dw1000-linux $ sudo insmod dw1000.ko
insmod: ERROR: could not insert module dw1000.ko: Unknown symbol in module
pi@raspberrypi:~/rsp_linux/dw1000-linux $

**Comment by xueliu** [comment]
Hi xingqing6210,

I am very sorry for this delay reply. I was very busy with my current work.

I believe that your rpi is lacking of ieee802154 modules. You should insert them before load the dw1000.ko. Please input following:

sudo modprobe mac802154
sudo modprobe ieee802154_socket

Regards

**Comment by xingqing6210** [comment]
Got it , thanks
