### ISSUE TITLE
./dw1000.ko: Invalid module format

### ISSUE THREAD

**Issue by justinleeyang** [xueliu/dw1000-linux#3]
hi,

insmod the dw1000.ko, but report the followong error:

./dw1000.ko: Invalid module format

I have already checked the kernal version ok.

> pi@raspberrypi:~/rsp_linux/dw1000-linux $
pi@raspberrypi:~/rsp_linux/dw1000-linux $
pi@raspberrypi:~/rsp_linux/dw1000-linux $ modinfo ./dw1000.ko
filename:       /home/pi/rsp_linux/dw1000-linux/./dw1000.ko
license:        GPL
author:         Xue Liu
description:    DW1000 IEEE 802.15.4 UWB Transceiver Driver
alias:          of:N*T*CdecaWave,dw1000C*
alias:          of:N*T*CdecaWave,dw1000
alias:          spi:dw1000
depends:
vermagic:       4.9.80-v7+ SMP mod_unload ARMv7 p2v8
pi@raspberrypi:~/rsp_linux/dw1000-linux $ uname -a
Linux raspberrypi 4.9.80-v7+ #2 SMP Sat Apr 21 10:19:20 UTC 2018 armv7l GNU/Linux
pi@raspberrypi:~/rsp_linux/dw1000-linux $ sudo insmod ./dw1000.ko
insmod: ERROR: could not insert module ./dw1000.ko: Invalid module format
pi@raspberrypi:~/rsp_linux/dw1000-linux $
>

**Comment by xueliu** [comment]
hi,

"Invalid module format" means the kernel running in your rpi and the kernel you compile the driver are not the same. Please have a check again.

**Comment by justinleeyang** [comment]
Hi,

the running kernel version in my rpi is 

`Linux version 4.9.80-v7+ (pi@raspberrypi) (gcc version 6.3.0 20170516 (Raspbian 6.3.0-18+rpi1+deb9u1) ) #2 SMP Sat Apr 21 10:19:20 UTC 2018`

the kernel I compile is 

`rpi-4.9.y-stable
`

**Comment by justinleeyang** [comment]
have you weixin ?

**Comment by justinleeyang** [comment]
or your kernel version is ?

**Comment by xueliu** [comment]
My Wechat: clockworkbird
