### ISSUE TITLE
 How to operate wpan0 network card for UWB positioning

### ISSUE THREAD

**Issue by WangBuYuan** [xueliu/dw1000-linux#4]
Hi liuxue:

I found the driver for dw3000 from the Android kernel and ported it to my own kernel, which generated a network card node and many sys nodes.

I noticed that your repo has also registered IEEE devices, which are in a similar state to mine. May I ask if you have generated WPAN network cards and how to operate them

I raised this issue in the qorvo community, but sadly, no one supported it
https://forum.qorvo.com/t/how-to-use-dw3000-linux-driver-ported-from-android-kernel/19095

大佬：
    我从安卓内核找了个dw3000的驱动移到了linux内核，驱动加载后生成了wpan网卡，请教下如何通过网卡进行uwb的操作呢？
    我在qorvo社区提了这个问题，但令人悲伤的是没人支持

**Comment by xueliu** [comment]
你好，
wpan有自己的配置工具，你可以看看这个https://linux-wpan.org/.
Android肯定也有自己的配置工具，我不是Android专家，你得自己找找看。

**Comment by WangBuYuan** [comment]
了解，感谢回复
